# Generated by Django 2.1.dev20180514000620 on 2018-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_auto_20180619_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default=0, max_length=30)),
                ('email', models.CharField(blank=True, default=0, max_length=30)),
                ('senha', models.CharField(blank=True, default=0, max_length=30)),
                ('mensagem', models.TextField(blank=True, default=0, max_length=30)),
                ('contato', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
